apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cp-kafka
  namespace: system-msg
spec:
  selector:
    matchLabels:
      app: cp-kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cp-kafka
    spec:
      containers:
      - image: confluentinc/cp-kafka-connect:latest
        name: cp-kafka
        env:
        - name: KAF1_PORT
          value: "tcp://kaf1:9092"
        - name: KAF1_PORT_9092_TCP
          value: "tcp://kaf1:9092"
        - name: KAF1_PORT_9092_TCP_ADDR
          value: "kaf1"
        - name: KAF1_PORT_9092_TCP_PORT
          value: "9092"
        - name: KAF1_PORT_9092_TCP_PROTO
          value: "tcp"
        - name: KAF1_SERVICE_HOST
          value: "kaf1"
        - name: KAF1_SERVICE_PORT
          value: "9092"
        - name: KAF1_SERVICE_PORT_PORT_9092
          value: "9092"
        - name: KAF2_PORT
          value: "tcp://kaf2:9092"
        - name: KAF2_PORT_9092_TCP
          value: "tcp://kaf1:9092"
        - name: KAF2_PORT_9092_TCP_ADDR
          value: "kaf2"
        - name: KAF2_PORT_9092_TCP_PORT
          value: "9092"
        - name: KAF2_PORT_9092_TCP_PROTO
          value: "tcp"
        - name: KAF2_SERVICE_HOST
          value: "kaf2"
        - name: KAF2_SERVICE_PORT
          value: "9092"
        - name: KAF2_SERVICE_PORT_PORT_9092
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "10.0.15.11"
        - name: KAFKA_MANAGER_PORT
          value: "tcp://10.0.15.11:30103"
        - name: KAFKA_MANAGER_PORT_80_TCP
          value: "tcp://10.0.15.11:30103"
        - name: KAFKA_MANAGER_PORT_80_TCP_ADDR
          value: "10.0.15.11"
        - name: KAFKA_MANAGER_PORT_80_TCP_PORT
          value: "80"
        - name: KAFKA_MANAGER_PORT_80_TCP_PROTO
          value: "tcp"
        - name: KAFKA_MANAGER_SERVICE_HOST
          value: "10.0.15.11"
        - name: KAFKA_MANAGER_SERVICE_PORT
          value: "80"
        - name: ZOO1_PORT
          value: "tcp://zoo1:2181"
        - name: ZOO1_PORT_2181_TCP
          value: "tcp://zoo1:2181"
        - name: ZOO1_PORT_2181_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_2181_TCP_PORT
          value: "2181"
        - name: ZOO1_PORT_2181_TCP_PROTO
          value: "tcp"
        - name: ZOO1_PORT_2888_TCP
          value: "tcp://zoo1:2888"
        - name: ZOO1_PORT_2888_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_2888_TCP_PORT
          value: "2888"
        - name: ZOO1_PORT_2888_TCP_PROTO
          value: "tcp"
        - name: ZOO1_PORT_3888_TCP
          value: "tcp://zoo1:3888"
        - name: ZOO1_PORT_3888_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_3888_TCP_PORT
          value: "3888"
        - name: ZOO1_PORT_3888_TCP_PROTO
          value: "tcp"
        - name: ZOO1_SERVICE_HOST
          value: "zoo1"
        - name: ZOO1_SERVICE_PORT
          value: "2181"
        - name: ZOO1_SERVICE_PORT_PORT_2181
          value: "2181"
        - name: ZOO1_SERVICE_PORT_PORT_2888
          value: "2888"
        - name: ZOO1_SERVICE_PORT_PORT_3888
          value: "3888"
        - name: ZOO2_PORT
          value: "tcp://zoo2:2181"
        - name: ZOO2_PORT_2181_TCP
          value: "tcp://zoo2:2181"
        - name: ZOO2_PORT_2181_TCP_ADDR
          value: "ZOO2"
        - name: ZOO2_PORT_2181_TCP_PORT
          value: "2181"
        - name: ZOO2_PORT_2181_TCP_PROTO
          value: "tcp"
        - name: ZOO2_PORT_2888_TCP
          value: "tcp://zoo2:2888"
        - name: ZOO2_PORT_2888_TCP_ADDR
          value: "ZOO2"
        - name: ZOO2_PORT_2888_TCP_PORT
          value: "2888"
        - name: ZOO2_PORT_2888_TCP_PROTO
          value: "tcp"
        - name: ZOO2_PORT_3888_TCP
          value: "tcp://zoo2:3888"
        - name: ZOO2_PORT_3888_TCP_ADDR
          value: "zoo2"
        - name: ZOO2_PORT_3888_TCP_PORT
          value: "3888"
        - name: ZOO2_PORT_3888_TCP_PROTO
          value: "tcp"
        - name: ZOO2_SERVICE_HOST
          value: "zoo2"
        - name: ZOO2_SERVICE_PORT
          value: "2181"
        - name: ZOO2_SERVICE_PORT_PORT_2181
          value: "2181"
        - name: ZOO2_SERVICE_PORT_PORT_2888
          value: "2888"
        - name: ZOO2_SERVICE_PORT_PORT_3888
          value: "3888"
