apiVersion: v1
kind: PersistentVolume
metadata:
  name: driver-cfg
  namespace: system-msg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /tmp/data/cp-kafka/jars
    server: 10.0.15.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: driver-cfg
  namespace: system-msg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sink-file
  namespace: system-msg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /tmp/data/cp-kafka/file
    server: 10.0.15.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sink-file
  namespace: system-msg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cp-kafka
  namespace: system-msg
spec:
  selector:
    matchLabels:
      app: cp-kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cp-kafka
    spec:
      containers:
      - image: confluentinc/cp-kafka-connect:latest
        name: cp-kafka
        env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kaf1:9092,kaf2:9092,kaf3:9092"
        - name: CONNECT_REST_PORT
          value: "28083"
        - name: CONNECT_GROUP_ID
          value: "quickstart-avro"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "quickstart-avro-config"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "quickstart-avro-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "quickstart-avro-status"
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://localhost:8081"
        - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "http://localhost:8081"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: "DEBUG"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/etc/kafka-connect/"
        volumeMounts:
        - name: driver-cfg
          mountPath: /etc/kafka-connect/jars
        - name: sink-file
          mountPath: /tmp/quickstart
      volumes:
      - name: driver-cfg
        persistentVolumeClaim:
          claimName: driver-cfg
      - name: sink-file
        persistentVolumeClaim:
          claimName: sink-file


