apiVersion: v1
kind: PersistentVolume
metadata:
  name: cp-kafka
  namespace: system-msg
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
    Retain
  nfs:
    path: /tmp/data/cp-kafka/jars
    server: 10.0.15.1
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cp-kafka-pvc
  namespace: system-msg
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 10Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cp-kafka
  namespace: system-msg
spec:
  selector:
    matchLabels:
      app: cp-kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cp-kafka
    spec:
      containers:
      - image: confluentinc/cp-kafka-connect:latest
        name: cp-kafka
        env:
        - name: KAF1_PORT_9092_TCP_ADDR
          value: "kaf1"
        - name: KAF1_PORT_9092_TCP_PORT
          value: "9092"
        - name: KAF1_PORT_9092_TCP_PROTO
          value: "tcp"
        - name: KAF1_SERVICE_HOST
          value: "kaf1"
        - name: KAF1_SERVICE_PORT
          value: "9092"
        - name: KAF2_PORT_9092_TCP_ADDR
          value: "kaf2"
        - name: KAF2_PORT_9092_TCP_PORT
          value: "9092"
        - name: KAF2_PORT_9092_TCP_PROTO
          value: "tcp"
        - name: KAF2_SERVICE_HOST
          value: "kaf2"
        - name: KAF2_SERVICE_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "kaf1,kaf2"
        - name: KAFKA_MANAGER_PORT_80_TCP_ADDR
          value: "kafka-manager"
        - name: KAFKA_MANAGER_PORT_80_TCP_PORT
          value: "80"
        - name: KAFKA_MANAGER_PORT_80_TCP_PROTO
          value: "tcp"
        - name: KAFKA_MANAGER_SERVICE_HOST
          value: "kafka-manager"
        - name: KAFKA_MANAGER_SERVICE_PORT
          value: "80"
        - name: ZOO1_PORT_2181_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_2181_TCP_PORT
          value: "2181"
        - name: ZOO1_PORT_2181_TCP_PROTO
          value: "tcp"
        - name: ZOO1_PORT_2888_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_2888_TCP_PORT
          value: "2888"
        - name: ZOO1_PORT_2888_TCP_PROTO
          value: "tcp"
        - name: ZOO1_PORT_3888_TCP_ADDR
          value: "zoo1"
        - name: ZOO1_PORT_3888_TCP_PORT
          value: "3888"
        - name: ZOO1_PORT_3888_TCP_PROTO
          value: "tcp"
        - name: ZOO1_SERVICE_PORT_PORT_2181
          value: "2181"
        - name: ZOO1_SERVICE_PORT_PORT_2888
          value: "2888"
        - name: ZOO1_SERVICE_PORT_PORT_3888
          value: "3888"
        - name: ZOO2_PORT_2181_TCP_ADDR
          value: "zoo2"
        - name: ZOO2_PORT_2181_TCP_PORT
          value: "2181"
        - name: ZOO2_PORT_2181_TCP_PROTO
          value: "tcp"
        - name: ZOO2_PORT_2888_TCP_ADDR
          value: "ZOO2"
        - name: ZOO2_PORT_2888_TCP_PORT
          value: "2888"
        - name: ZOO2_PORT_2888_TCP_PROTO
          value: "tcp"
        - name: ZOO2_PORT_3888_TCP_ADDR
          value: "zoo2"
        - name: ZOO2_PORT_3888_TCP_PORT
          value: "3888"
        - name: ZOO2_PORT_3888_TCP_PROTO
          value: "tcp"
        - name: ZOO2_SERVICE_PORT_PORT_2181
          value: "2181"
        - name: ZOO2_SERVICE_PORT_PORT_2888
          value: "2888"
        - name: ZOO2_SERVICE_PORT_PORT_3888
          value: "3888"
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: "kaf1:9092,kaf2:9092"
        - name: CONNECT_GROUP_ID
          value: "connect-cluster"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: "connect-config"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: "connect-offsets"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: "connect-status"
        - name: CONNECT_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: "org.apache.kafka.connect.json.JsonConverter"
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: "localhost"
        - name: CONNECT_PLUGIN_PATH
          value: "/usr/share/java,/etc/kafka-connect/"
        volumeMounts:
        - name: driver-cfg
          mountPath: /etc/kafka-connect/jars
      volumes:
      - name: driver-cfg
        persistentVolumeClaim:
          claimName: cp-kafka-pvc

